# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy all source files
COPY . .

# Build the TypeScript source
RUN npm run build

# Expose any necessary ports if needed (optional)
# EXPOSE 3000

CMD ["node", "build/index.js"]
